version: '3.7'
services:
  web:
    build: ./app
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./app :/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
